<?php
/**
 * Created by PhpStorm.
 * User: Nikita Zimin
 * Date: 30.01.2022
 * Time: 13:28
 */

/** @var \App\Model\User $user */
$user = $this->user;
/** @var \App\Model\Post[] $posts */
$posts = $this->posts;
?>

Вы вошли как <?= $user->getName() ?>

<form action="/user/logout">
    <input type="submit" value="Выйти">
</form>


<?php
if ($result = $this->result): ?>
    <p class="result" style="color: green;"><?= $result ?></p>
<?php
endif; ?>


<?php
if ($error = $this->error): ?>
    <p class="error" style="color: red"><?= $error ?></p>
<?php
endif; ?>


<div class="blog_container">
    <div class="new_post">
        <h2>Отправить сообщение</h2>
        <form action="/blog/post" method="post" enctype="multipart/form-data">
            <p>Сообщение: <textarea rows="10" cols="45" name="message"></textarea></p>
            <p>Прикрепить изображение: <input type="file" name="image"></p>
            <p><input type="submit" value="Отправить"></p>
        </form>
    </div>

    <div class="posts_container">
        <h2>Последние сообщения в блоге:</h2>
        <?php
        if ($posts): ?>
            <?php
            foreach ($posts as $i => $post): ?>
                <div class="post-<?= $i % 2 === 0 ? 'odd' : 'even' ?>">
                    <p class="message">
                        <span class="author"> <?= $post->getUserName() ?>:</span> <?= $post->getMessage() ?>
                    </p>
                    <p class="post-footer">
                        <?= $post->getCreatedAt() ?>

                        <?php if ($user->getIsAdmin()): ?>
                        <a href="/blog/delete-post?id=<?= $post->getId() ?>">Удалить</a>
                        <?php endif; ?>
                    </p>
                </div>
            <?php
            endforeach ?>
        <?php
        else: ?>
            В блоге еще никто не писал :(
        <?php
        endif ?>
    </div>
</div>

<style>
    .posts_container {
        display: grid;
        grid-gap: 10px;
    }

    .post-footer {
        font-size: small;
    }

    .author {
        font-weight: bold;
    }
    .post-odd {
        background: azure;
    }

    .post-even {
        background: beige;
    }
</style>
