<?php
/**
 * Register template
 *
 * Created by PhpStorm.
 * User: Nikita Zimin
 * Date: 29.01.2022
 * Time: 19:16
 *
 */
?>

Регистрация:
<form action="/user/register" method="post">
    Имя: <input type="text" name="name"> <br>
    Email: <input type="text" name="email"> <br>
    Пароль: <input type="password" name="password"> <br>
    Подтверждение пароля: <input type="password" name="password_confirmation"> <br>
    <input type="submit" value="Зарегистрироваться">
</form>
<br>
<br>

Войти
<form action="/user/login" method="post">
    Email: <input type="text" name="email"> <br>
    Пароль: <input type="password" name="password"> <br>
    <input type="submit" value="Войти">
</form>

<br>
<br>
<?php
if ($error = $this->error): ?>
    <span style="color: red"><?= $error ?></span>
<?php
endif; ?>
